### PR TITLE
cfetch: Improved test expressions, parameter expansion, and shellcheck

### PR DESCRIPTION
**Pull request by owl4ce**
Should be tested first, but I can confirm that it's a bit faster.

### CODE REVIEW

**Comment by owl4ce** [comment]
I just thinking about printing multiple package managers support, but it's up to you whether to support it or not.

**Comment by ashtrath** [comment]
> I just thinking about printing multiple package managers support, but it's up to you whether to support it or not.

That's will be awesome! I might consider how much it's affecting the speed, but we can give it a try.

**Comment by owl4ce** [comment]
> That's will be awesome! I might consider how much it's affecting the speed, but we can give it a try.

## Implemented at https://github.com/Dyzean/coffee-fetch/pull/2/commits/e6d3d1dd5d3d3ad6b75584d79a5ae5ee8cf9e0c7 

2022-02-05-135518_1301x748_scrot

**Comment by ashtrath** [comment]
Awesome! There's no "real" proof yet for its speed as it still depends on the speed of the package manager to count the package, but this is a very good result.

**Pull request merged**
