### PR TITLE
Added uptime with better readability

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ashtrath** [comment]
GNU Uptime does not have a `-p` flag, only ProcPS Uptime has it. This is a fetching tool meant to work on _all_ unix* system.

**Comment by mr-cheffy** [comment]
Yes they do have it as they work on my system

**Comment by ashtrath** [comment]
> Yes they do have it as they work on my system

only on your system, as i said GNU Uptime doesn't have `-p` flags option, on some linux distro or unix system that doesn't have ProcPS installed will complaint `uptime: invalid option -- 'p'`

**Comment by mr-cheffy** [comment]
Hm...

**Comment by mr-cheffy** [comment]
Alr close this PR then

**Pull request closed without merging**
